// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEWZZFvlrJOLtqAZGsknwuYqpjq0SbZPA',
    appId: '1:579255901762:web:1b039a1b5034d5e5d617db',
    messagingSenderId: '579255901762',
    projectId: 'flash-chat-app-a93be',
    authDomain: 'flash-chat-app-a93be.firebaseapp.com',
    storageBucket: 'flash-chat-app-a93be.appspot.com',
    measurementId: 'G-RLJ6H387V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU33OFTv74-tjPRkPt6DsRKlX01RE9OdY',
    appId: '1:579255901762:android:62f81026404b78ccd617db',
    messagingSenderId: '579255901762',
    projectId: 'flash-chat-app-a93be',
    storageBucket: 'flash-chat-app-a93be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnJNa3G7cqYD9K0mTAHQo5at6q_k3lqkU',
    appId: '1:579255901762:ios:c602d11bcc313b84d617db',
    messagingSenderId: '579255901762',
    projectId: 'flash-chat-app-a93be',
    storageBucket: 'flash-chat-app-a93be.appspot.com',
    iosBundleId: 'io.codersio.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnJNa3G7cqYD9K0mTAHQo5at6q_k3lqkU',
    appId: '1:579255901762:ios:85217e25ac5c8627d617db',
    messagingSenderId: '579255901762',
    projectId: 'flash-chat-app-a93be',
    storageBucket: 'flash-chat-app-a93be.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEWZZFvlrJOLtqAZGsknwuYqpjq0SbZPA',
    appId: '1:579255901762:web:fe97d44edbcc21edd617db',
    messagingSenderId: '579255901762',
    projectId: 'flash-chat-app-a93be',
    authDomain: 'flash-chat-app-a93be.firebaseapp.com',
    storageBucket: 'flash-chat-app-a93be.appspot.com',
    measurementId: 'G-WZM7TYQ3Q4',
  );
}
